### ISSUE TITLE
ET Bug 

### ISSUE THREAD

**Issue by Zlexz** [MCPrison/Server#169]
https://youtu.be/BIWMltapiDM

1. ET Bug:

For some reason, I get 31 etokens per block mined, even though I don't have any enchants on pick/bp/gang or an active booster.

EDIT: It was 45 ets per block mined yesterday.
Tested on alt it only gives me 1.
Asked someone else and he said he gets 3.

Ignore the second part of the video, I'll make a more explicit one + a new issue.

**Comment by HijackingMC** [comment]
Should be fixed, can you test it @Zlexz

**Comment by Zlexz** [comment]
I still receive 35 etokens per block mined with no enchants. @HijackingMC
